Lusas toolkit #398 fix bug for incorrect id in error message
BHoM/Lusas_Toolkit pull request #400
Opened 2024-03-11 12:13 UTC by KalleEdstroem

### Issues addressed by this PR

Closes #397 
Closes #398 

Fixed two bug related to Panel with openings. Giving m_mergeTolerance a default value and correcting Ids in Error message.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Lusas_Toolkit/%23396-AddSupportForPanelWithOpenings?csf=1&web=1&e=uOsKNh

### Changelog

- Added default value for `m_mergeTolerance` to be `Tolerance.Distance` (1E-6).
- Changed Ids in Error message regarding invalid `Openings` in `Create`/`Surface.cs`

2024-03-11 12:16 UTC, KalleEdstroem commented
You still get a `-1` back for ID of the Opening that never gets created since its `Edges` defining it is not Planar.

2024-03-12 15:49 UTC, peterjamesnugent requested changes
Thanks @KalleEdstroem, where the `Opening` does not get created, I do not think including the `-1` is useful.

Can we also add an `else` statement here:
https://github.com/BHoM/Lusas_Toolkit/blob/ef9ff1dd2dfccfd043c01fb2a5986acd91e347dc/Lusas_Adapter/LusasAdapter.cs#L174-L178

You could have a scenario where the user has a model with a tolerance of `1E-3`, and then the Adapter in the background is set to `1E-6`. Within the `else` statement we should add a warning saying a merge tolerance has not been set and has defaulted to 1E-6.

2024-03-12 15:49 UTC, peterjamesnugent commented on Lusas_Adapter/CRUD/Create/Elements/Surface.cs
> +                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {lusasSurface.getID()} intersects with at least one Edge defining the Opening {openingID}, Opening not creat
```suggestion
                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {lusasSurface.getID()} intersects with at least one Edge defining the Opening, Opening not created.");
```

2024-03-12 15:49 UTC, peterjamesnugent commented on Lusas_Adapter/CRUD/Create/Elements/Surface.cs
> +                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {lusasSurface.getID()} is not Coplanar with the Opening {openingID}, Opening not created.");
```suggestion
                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {lusasSurface.getID()} is not Coplanar with the Opening, Opening not created.");
```

2024-03-12 17:14 UTC, KalleEdstroem commented on Lusas_Adapter/CRUD/Create/Elements/Surface.cs
> +                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {lusasSurface.getID()} intersects with at least one Edge defining the Opening {openingID}, Opening not creat
Yes, agree that it is not necessary.

2024-03-12 17:15 UTC, KalleEdstroem commented on Lusas_Adapter/CRUD/Create/Elements/Surface.cs
> +                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {lusasSurface.getID()} is not Coplanar with the Opening {openingID}, Opening not created.");
Agree, same as above.

2024-03-13 09:35 UTC, peterjamesnugent requested changes
I have tested using the scripts, have with the warning on the Adapter, just some minor changes for the `Panel` warnings.

2024-03-13 09:35 UTC, peterjamesnugent commented on Lusas_Adapter/CRUD/Create/Elements/Surface.cs
> +                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {lusasSurface.getID()} is not Coplanar with the Opening, Opening not created.");
```suggestion
                    Engine.Base.Compute.RecordError($"The geometry defining Panel {lusasSurface.getID()} is not Coplanar with an Opening, this Opening has not been created.");
```

2024-03-13 09:35 UTC, peterjamesnugent commented on Lusas_Adapter/CRUD/Create/Elements/Surface.cs
> +                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {lusasSurface.getID()} intersects with at least one Edge defining the Opening, Opening not created.");
```suggestion
                    Engine.Base.Compute.RecordError($"At least one Edge defining Panel {lusasSurface.getID()} intersects with at least one Edge defining an Opening, this Opening has not been created.");
```

2024-03-13 09:35 UTC, peterjamesnugent commented on Lusas_Adapter/CRUD/Create/Elements/Surface.cs
> +                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Surface {lusasSurface.getID()}, Opening not created.");
```suggestion
                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Panel {lusasSurface.getID()}, this Opening has not been created.");
```

2024-03-14 10:49 UTC, peterjamesnugent approved these changes
Functionality has not changed, just the contents of the warning messages. Happy all my comments have been addressed.

2024-03-14 10:49 UTC, peterjamesnugent commented
@BHoMBot check compliance
@BHoMBot check required

2024-03-14 22:40 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2024-03-14 22:52 UTC, peterjamesnugent commented
@BHoMBot check ready-to-merge

2024-03-14 22:53 UTC, merged